name: Android Lint CI

on:
  push:
    paths:
      - "features/products/list/**"
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "features/products/list/**"

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Runs Products List Unit test
      run: ./gradlew features:products:list:library:testDebugUnitTest
