name: Product Detail Testing

on:
  push:
    paths:
      - "features/products/detail/**"
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - "features/products/detail/**"

jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Runs Product Details Unit test
        run: ./gradlew features:products:detail:library:testDebugUnitTest --stacktrace
      - name: Runs Product Detail Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew features:products:detail:app:connectedDebugAndroidTest --stacktrace
